.TH SKELETON 1 "21 Mar 2013" "skeleton 0.2.3"

.SH NAME
skeleton \- a minesweeper clone based on the EFL

.SH SYNOPSIS
.B skeleton
[-d] [-f] [-t=THEME] [-m=MINES] [-L] [-C] [-V] [-h]

.SH DESCRIPTION

Skeleton is a demo application to show how to integrate EFL and autotools into a
cross platform build. You should be able to generate an executable easily for all
target supported by EFL with this skeleton.

With no option, the program starts and display an Hello World.


.SH OPTIONS

.TP
.B -L, --license
Show license.

.TP
.B -C, --copyright
Show copyright.

.TP
.B -V, --version
Show program version.

.TP
.B -h, --help
Print list of options with short description.


.SH BUGS

Reports are welcome.


.SH HOMEPAGE

http://enlightenment.org


.SH AUTHORS

Cedric Bail <cedric.bail@samsung.com> and various contributors.
